### Registro de Usuarios
POST http://127.0.0.1:8000/api/v1/auth/register
Accept: application/json
Content-Type: application/json

{
    "name": "tauro",
    "email": "tauro@mail.com",
    "password": "tauro123",
    "c_password": "tauro123"
}

### Autenticación (login)

POST http://127.0.0.1:8000/api/v1/auth/login
Accept: application/json
Content-Type: application/json

{
    "email": "tauro@mail.com",
    "password": "tauro123"
}

### Perfil

GET http://127.0.0.1:8000/api/v1/auth/profile
Accept: application/json
Authorization: Bearer 7|Wm0ua9gTwzpOKhZc2dQPA61IDVT1HD5tptL13nAT0bf327d0


### salir

POST http://127.0.0.1:8000/api/v1/auth/logout
Accept: application/json
Authorization: Bearer 7|Wm0ua9gTwzpOKhZc2dQPA61IDVT1HD5tptL13nAT0bf327d0





